version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
